### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/ckanext-cmre#9]
Customize logo and colors

**Comment by chpicone** [comment]
[Here ](https://docs.google.com/presentation/d/1keDJZ8AzS8oOZqLwPgMjb7EKWBwKirpfFe6ZfbRfJs0/edit?usp=sharing)mockups provided by CMRE

**Comment by chpicone** [comment]
We received text and some additional requirements in a [PPT slide](https://docs.google.com/presentation/d/1U1GgqTHHUxVB4ODUvhp6oZqQi2iveBcUeKa5uqaZNtE/edit?usp=sharing).
@allyoucanmap can you check if it is possible to do them or to propose an alternative?

**Comment by chpicone** [comment]
Required activities:
- Remove from the header the **Register** item
- Hide **Organizations** and **Groups** for anonymous users
![image](https://user-images.githubusercontent.com/2872823/96682997-dc203180-1379-11eb-95d3-734a81efa8f2.png)
- Facet **Overall Data Category** is missing and we need to move it under the item "Sea Trial"
- Remove section Organizations (in the left panel) from the dataset page:
![image](https://user-images.githubusercontent.com/2872823/96683202-1be71900-137a-11eb-8889-30e850503c1a.png)
- Create 2 tabs
- **instrument**: information to put in a table
- remove **additional info**
- in the page of the specific resource remove the social icons from the left panel:
![image](https://user-images.githubusercontent.com/2872823/96683364-66689580-137a-11eb-999d-7a326141188f.png)

**Comment by chpicone** [comment]
CMRE asks to remove the link to the page of the specific resource (last point of the previous comment)

**Comment by etj** [comment]
I'll work on these two:
- [ ] Remove from the header the Register item.
  There's a configuration item in CKAN that controls wheter users can register or not.
  I'll create an issue for @lpasquali about it.
- [ ] Facet Overall Data Category is missing and we need to move it under the item "Sea Trial"
  This is something that needs to be implemented via python

**Comment by allyoucanmap** [comment]
@chpicone 

> - [ ] in the page of the specific resource remove the social icons from the left panel:

we resolved this by removing the link from the Explore button as requested in you second comment

> CMRE asks to remove the link to the page of the specific resource (last point of the previous comment)

**Comment by chpicone** [comment]
Yes. It is correct @allyoucanmap

**Comment by simboss** [comment]
@christian, I am removeing @etj from this issue.

I am not sure this issue can be closed though.
